spring:
  security:
    user:
      name: ${USERNAME:admin}
      password: ${PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always