spring:
  #处理 FeignClient 重名问题
  main:
    allow-bean-definition-overriding: on
  cloud:
    gateway:
      # 配置路由规则
      routes:
        - id: lion-auth
          uri: lb://lion-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: lion-demo-provider
          uri: lb://lion-demo-provider
          predicates:
            - Path=/demo/provider/**
          filters:
            - StripPrefix=2

        - id: lion-demo-consumer
          uri: lb://lion-demo-consumer
          predicates:
            - Path=/demo/consumer/**
          filters:
            - StripPrefix=2

    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8858}
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
    sender:
      type: rabbit
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:lion}

#开启sentinel断路器
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always